import sys

print("About to fail...")

sys.exit(1)
