# Translations template for nova_powervm.
# Copyright 2015, 2017 IBM Corp.
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2017.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 4.0.1.dev5\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2017-04-20 10:07-0400\n"
"PO-Revision-Date: 2017-04-20 10:07-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.4.0\n"

#: nova_powervm/virt/powervm/driver.py:1531
msgid "Live migration timed out. Aborting migration"
msgstr "Die Livemigration hat das zulässige Zeitlimit überschritten. Die Migration wird abgebrochen."

#: nova_powervm/virt/powervm/live_migration.py:376
msgid "Live migration failed."
msgstr "Die Livemigration ist fehlgeschlagen."

#: nova_powervm/virt/powervm/live_migration.py:439
#, python-format
msgid "Migration recover failed with error: %s"
msgstr "Die Wiederherstellung der Migration ist fehlgeschlagen mit Fehler: %s"

#: nova_powervm/virt/powervm/live_migration.py:467
msgid ""
"Abort of live migration has failed. This is non-blocking. Exception is "
"logged below."
msgstr ""
"Der Abbruch der Livemigration ist fehlgeschlagen. Dies ist nicht blockierend. Die Ausnahmebedingung wird "
"unten protokolliert."

#: nova_powervm/virt/powervm/vif.py:119
#, python-format
msgid "Custom VIF event push failed.  %s"
msgstr "Übertragen des benutzerdefinierten VIF-Ereignisses mit Push-Operation fehlgeschlagen. %s"

#: nova_powervm/virt/powervm/vif.py:370
#, python-format
msgid "Unable to unplug VIF with mac %(mac)s for instance %(inst)s."
msgstr "Der VIF mit MAC %(mac)s für Instanz %(inst)s konnte nicht getrennt werden."

#: nova_powervm/virt/powervm/vm.py:647
#, python-format
msgid "Virtual machine delete failed: LPARID=%s"
msgstr "Das Löschen der virtuellen Maschine ist fehlgeschlagen: LPARID=%s"

#: nova_powervm/virt/powervm/disk/localdisk.py:263
#, python-format
msgid "Disk %s not found during resize."
msgstr "Bei der Größenänderung wurde die Platte %s nicht gefunden."

#: nova_powervm/virt/powervm/disk/ssp.py:333
#, python-format
msgid "Error checking for shared storage. exception=%s"
msgstr "Fehlerprüfung für den gemeinsam genutzten Speicher. Ausnahmebedingung: %s"

#: nova_powervm/virt/powervm/nvram/manager.py:109
#: nova_powervm/virt/powervm/nvram/manager.py:178
#, python-format
msgid "Could not update NVRAM: %s"
msgstr "Der nicht flüchtige Arbeitsspeicher konnte nicht aktualisiert werden: %s"

#: nova_powervm/virt/powervm/tasks/network.py:66
#, python-format
msgid ""
"Unable to remove VIFs from instance %(inst)s because the system is not in a "
"correct state.  The reason reported by the system is: %(reason)s"
msgstr ""
"VIFs konnten nicht aus der Instanz %(inst)s entfernt werden, weil sich das System nicht in "
"einem korrekten Zustand befindet. Das System meldete den folgenden Grund: %(reason)s"

#: nova_powervm/virt/powervm/tasks/network.py:154
#, python-format
msgid ""
"Unable to create VIF(s) for instance %(sys)s.  The VM was in a state where "
"VIF plugging is not acceptable.  The reason from the system is: %(reason)s"
msgstr ""
"Es konnten keine VIF(s) für Instanz %(sys)s erstellt werden. Die VM befand sich in einem Zustand, "
"der das Verbinden von VIFs nicht zulässt. Das System meldete den folgenden Grund: %(reason)s"

#: nova_powervm/virt/powervm/tasks/network.py:207
#, python-format
msgid "Error waiting for VIF to be created for instance %(sys)s"
msgstr "Beim Warten auf die VIF-Erstellung für Instanz %(sys)s ist ein Fehler aufgetreten."

#: nova_powervm/virt/powervm/tasks/network.py:221
#, python-format
msgid "VIF Plug failure for callback on event %(event)s for instance %(uuid)s"
msgstr "VIF Plug-Ausfall für den Callback bei Ereignis %(event)s für Instanz %(uuid)s"

#: nova_powervm/virt/powervm/tasks/vm.py:283
#, python-format
msgid "Unable to store NVRAM for instance %(name)s. Exception: %(reason)s"
msgstr "Der nicht flüchtige Arbeitsspeicher konnte für die Instanz %(name)s nicht gespeichert werden. Ausnahmebedingung: %(reason)s"

#: nova_powervm/virt/powervm/tasks/vm.py:313
#, python-format
msgid "Unable to delete NVRAM for instance %(name)s. Exception: %(reason)s"
msgstr "Der nicht flüchtige Arbeitsspeicher konnte für die Instanz %(name)s nicht gelöscht werden. Ausnahmebedingung: %(reason)s"

#: nova_powervm/virt/powervm/volume/iscsi.py:214
#, python-format
msgid "Cannot detach volumes from virtual machine: %s"
msgstr "Die Zuordnung der Datenträger zur folgenden virtuellen Maschine konnte nicht aufgehoben werden: %s"

#: nova_powervm/virt/powervm/volume/iscsi.py:216
#: nova_powervm/virt/powervm/volume/vscsi.py:340
#, python-format
msgid "Error: %s"
msgstr "Fehler: %s"

#: nova_powervm/virt/powervm/volume/npiv.py:517
#, python-format
msgid ""
"Mappings were not able to find a proper VIOS. The port mappings were %s."
msgstr ""
"Die DNA-Grobanalysen konnten keinen geeigneten virtuellen E/A-Server finden. Die Portzuordnungen waren %s."

#: nova_powervm/virt/powervm/volume/vscsi.py:338
msgid "Cannot detach volumes from virtual machine"
msgstr "Die Zuordnung der Datenträger zur virtuellen Maschine konnte nicht aufgehoben werden."

# ENGL1SH_VERS10N 32661_5 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 44
# T9N_SH1P_STR1NG PV133AAP001 2
