# Translations template for nova_powervm.
# Copyright 2015, 2017 IBM Corp.
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2017.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 4.0.1.dev5\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2017-04-20 10:07-0400\n"
"PO-Revision-Date: 2017-04-20 10:07-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.4.0\n"

#: nova_powervm/virt/powervm/driver.py:1531
msgid "Live migration timed out. Aborting migration"
msgstr "Истек тайм-аут оперативной миграции. Миграция прервана"

#: nova_powervm/virt/powervm/live_migration.py:376
msgid "Live migration failed."
msgstr "Сбой оперативной миграции."

#: nova_powervm/virt/powervm/live_migration.py:439
#, python-format
msgid "Migration recover failed with error: %s"
msgstr "Не удалось восстановить миграцию. Ошибка: %s"

#: nova_powervm/virt/powervm/live_migration.py:467
msgid ""
"Abort of live migration has failed. This is non-blocking. Exception is "
"logged below."
msgstr ""
"Сбой прерывания оперативной миграции. Это неблокирующая ситуация. Исключительная ситуация "
"описана ниже."

#: nova_powervm/virt/powervm/vif.py:119
#, python-format
msgid "Custom VIF event push failed.  %s"
msgstr "Не удалось отправить пользовательское событие VIF.  %s"

#: nova_powervm/virt/powervm/vif.py:370
#, python-format
msgid "Unable to unplug VIF with mac %(mac)s for instance %(inst)s."
msgstr "Не удалось отсоединить VIF с mac %(mac)s для экземпляра %(inst)s."

#: nova_powervm/virt/powervm/vm.py:647
#, python-format
msgid "Virtual machine delete failed: LPARID=%s"
msgstr "Сбой удаления виртуальной машины: LPARID=%s"

#: nova_powervm/virt/powervm/disk/localdisk.py:263
#, python-format
msgid "Disk %s not found during resize."
msgstr "В процессе изменения размера не найден диск %s."

#: nova_powervm/virt/powervm/disk/ssp.py:333
#, python-format
msgid "Error checking for shared storage. exception=%s"
msgstr "Ошибка проверки общей памяти. Исключительная ситуация=%s"

#: nova_powervm/virt/powervm/nvram/manager.py:109
#: nova_powervm/virt/powervm/nvram/manager.py:178
#, python-format
msgid "Could not update NVRAM: %s"
msgstr "Не удалось обновить NVRAM: %s"

#: nova_powervm/virt/powervm/tasks/network.py:66
#, python-format
msgid ""
"Unable to remove VIFs from instance %(inst)s because the system is not in a "
"correct state.  The reason reported by the system is: %(reason)s"
msgstr ""
"Не удалось удалить VIF из экземпляра %(inst)s, так как система находится в "
"некорректном состоянии.  Сообщенная системой причина: %(reason)s"

#: nova_powervm/virt/powervm/tasks/network.py:154
#, python-format
msgid ""
"Unable to create VIF(s) for instance %(sys)s.  The VM was in a state where "
"VIF plugging is not acceptable.  The reason from the system is: %(reason)s"
msgstr ""
"Не удалось создать VIF для экземпляра %(sys)s.  VM находится в том состоянии, "
"в котором невозможно подсоединить VIF.  Сообщенная системой причина: %(reason)s"

#: nova_powervm/virt/powervm/tasks/network.py:207
#, python-format
msgid "Error waiting for VIF to be created for instance %(sys)s"
msgstr "Ошибка при ожидании создания VIF для экземпляра %(sys)s"

#: nova_powervm/virt/powervm/tasks/network.py:221
#, python-format
msgid "VIF Plug failure for callback on event %(event)s for instance %(uuid)s"
msgstr "Сбой подключения VIF для обратного вызова по событию %(event)s для экземпляра %(uuid)s"

#: nova_powervm/virt/powervm/tasks/vm.py:283
#, python-format
msgid "Unable to store NVRAM for instance %(name)s. Exception: %(reason)s"
msgstr "Не удалось сохранить NVRAM для экземпляра %(name)s. Исключительная ситуация: %(reason)s"

#: nova_powervm/virt/powervm/tasks/vm.py:313
#, python-format
msgid "Unable to delete NVRAM for instance %(name)s. Exception: %(reason)s"
msgstr "Ошибка при удалении NVRAM для экземпляра %(name)s. Исключительная ситуация: %(reason)s"

#: nova_powervm/virt/powervm/volume/iscsi.py:214
#, python-format
msgid "Cannot detach volumes from virtual machine: %s"
msgstr "Не удалось отключить тома от виртуальной машины: %s"

#: nova_powervm/virt/powervm/volume/iscsi.py:216
#: nova_powervm/virt/powervm/volume/vscsi.py:340
#, python-format
msgid "Error: %s"
msgstr "Ошибка: %s"

#: nova_powervm/virt/powervm/volume/npiv.py:517
#, python-format
msgid ""
"Mappings were not able to find a proper VIOS. The port mappings were %s."
msgstr ""
"Не удалось найти подходящий VIOS по связям. Связи порта: %s."

#: nova_powervm/virt/powervm/volume/vscsi.py:338
msgid "Cannot detach volumes from virtual machine"
msgstr "Не удалось отключить тома от виртуальной машины"

# ENGL1SH_VERS10N 32661_5 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 44
# T9N_SH1P_STR1NG PV133AAP001 2
